const IELTS_WORD_BANK = [
  ['allocate','分配；拨出','Governments should allocate more funding to public transport.'],
  ['significant','显著的；重要的','There was a significant increase in overseas student numbers.'],
  ['consistent','持续一致的','Consistent practice makes weaknesses visible earlier.'],
  ['maintain','维持；保持','Cities must maintain a balance between growth and sustainability.'],
  ['beneficial','有益的','Regular feedback is beneficial for IELTS writing improvement.'],
  ['constraint','限制；约束','Time is a major constraint during the reading test.'],
  ['evidence','证据','A strong essay needs clear evidence and explanation.'],
  ['approach','方法；处理方式','A strategic approach can reduce repeated mistakes.'],
  ['indicate','表明；显示','The figures indicate a steady rise after 2015.'],
  ['priority','优先事项','Vocabulary review should be a daily priority.'],
  ['acquire','获得；习得','Children acquire language through repeated exposure.'],
  ['adapt','适应；改编','Workers must adapt to rapid technological change.'],
  ['adequate','足够的；合格的','Many rural areas lack adequate medical services.'],
  ['alternative','替代方案','Cycling is a practical alternative to driving.'],
  ['annual','每年的','The annual survey shows changing attitudes to education.'],
  ['assess','评估','Teachers should assess both accuracy and fluency.'],
  ['assumption','假设','The argument is based on a questionable assumption.'],
  ['authority','权威；当局','Local authorities should improve waste management.'],
  ['capacity','能力；容量','The stadium has a capacity of 40,000 people.'],
  ['category','类别','The data can be divided into three categories.'],
  ['challenge','挑战','Climate change is a global challenge.'],
  ['circumstance','情况；环境','People behave differently under stressful circumstances.'],
  ['clarify','澄清','The chart clarifies the relationship between income and age.'],
  ['coherent','连贯的','A coherent essay is easy for the examiner to follow.'],
  ['collapse','倒塌；崩溃','The old bridge collapsed after heavy rain.'],
  ['commute','通勤','Many employees commute by train.'],
  ['community','社区','Libraries play an important role in the community.'],
  ['compensate','补偿','The company agreed to compensate affected customers.'],
  ['complex','复杂的','Urban transport is a complex issue.'],
  ['component','组成部分','Vocabulary is one component of language proficiency.'],
  ['concentrate','集中注意力','It is difficult to concentrate in a noisy room.'],
  ['consequence','后果','Poor planning can have serious consequences.'],
  ['considerable','相当大的','There was a considerable difference between the two groups.'],
  ['consume','消耗；消费','Modern households consume more energy than before.'],
  ['contribute','贡献；促成','Exercise contributes to better mental health.'],
  ['controversial','有争议的','Animal testing remains a controversial topic.'],
  ['conventional','传统的','Conventional classrooms still have several advantages.'],
  ['cooperate','合作','Countries need to cooperate on environmental protection.'],
  ['criteria','标准','IELTS writing is assessed using clear criteria.'],
  ['crucial','关键的','Time management is crucial in the reading test.'],
  ['decline','下降；衰退','The number of visitors declined after 2018.'],
  ['dedicate','投入；奉献','She dedicated two hours a day to exam preparation.'],
  ['demonstrate','证明；展示','The results demonstrate the value of early intervention.'],
  ['derive','源自；获得','Many English words derive from Latin.'],
  ['detect','发现；察觉','The system can detect repeated mistakes.'],
  ['device','设备','Mobile devices are widely used in education.'],
  ['dimension','方面；维度','The problem has an economic dimension.'],
  ['diminish','减少；削弱','Excessive screen time may diminish attention span.'],
  ['distinct','不同的；清楚的','The two methods have distinct advantages.'],
  ['domestic','国内的；家庭的','Domestic tourism increased during the holiday.'],
  ['efficient','高效的','Public transport is more efficient in dense cities.'],
  ['emerge','出现','New problems may emerge as technology develops.'],
  ['emphasis','强调','The course places emphasis on critical thinking.'],
  ['enable','使能够','Online platforms enable flexible learning.'],
  ['encounter','遇到','Students may encounter unfamiliar vocabulary.'],
  ['enhance','提高；增强','Feedback can enhance writing performance.'],
  ['ensure','确保','Governments should ensure equal access to education.'],
  ['environment','环境','A quiet environment helps concentration.'],
  ['estimate','估计','Experts estimate that demand will continue to rise.'],
  ['evaluate','评价','Learners should evaluate their own mistakes.'],
  ['expand','扩大','The city plans to expand its metro system.'],
  ['exposure','接触；暴露','Regular exposure to English improves listening skills.'],
  ['factor','因素','Cost is an important factor in decision-making.'],
  ['feature','特征；特点','The main feature of the app is spaced review.'],
  ['fluctuate','波动','Oil prices fluctuated throughout the year.'],
  ['function','功能；起作用','Schools function as social spaces.'],
  ['generate','产生','Renewable energy can generate electricity with less pollution.'],
  ['gradual','逐渐的','The graph shows a gradual increase.'],
  ['highlight','突出；强调','The report highlights several risks.'],
  ['identify','识别','Students need to identify keywords quickly.'],
  ['impact','影响','Tourism has a major impact on local economies.'],
  ['implement','实施','The policy was implemented in 2022.'],
  ['incentive','激励','Tax cuts can provide an incentive for investment.'],
  ['income','收入','Average income rose steadily.'],
  ['inevitable','不可避免的','Some degree of change is inevitable.'],
  ['infrastructure','基础设施','Better infrastructure can reduce traffic congestion.'],
  ['initial','最初的','The initial results were encouraging.'],
  ['innovation','创新','Innovation is essential for economic growth.'],
  ['insufficient','不足的','Insufficient sleep affects learning efficiency.'],
  ['integrate','整合','Technology should be integrated into education carefully.'],
  ['interaction','互动','Classroom interaction can improve confidence.'],
  ['interpret','解释；理解','Candidates must interpret data accurately.'],
  ['invest','投资','Many countries invest heavily in renewable energy.'],
  ['justify','证明合理','Writers need to justify their opinions with examples.'],
  ['legal','法律的','There are legal limits on advertising to children.'],
  ['majority','大多数','The majority of respondents preferred online booking.'],
  ['method','方法','This method is useful for vocabulary review.'],
  ['minority','少数','A minority of students chose science subjects.'],
  ['network','网络','A strong transport network supports economic activity.'],
  ['obtain','获得','Researchers obtained data from three schools.'],
  ['occupy','占据','Housing occupies a large proportion of household budgets.'],
  ['occur','发生','Errors often occur under time pressure.'],
  ['participate','参与','Students should participate in class discussions.'],
  ['perceive','认为；感知','Some people perceive online learning as less effective.'],
  ['policy','政策','The policy aims to reduce air pollution.'],
  ['potential','潜在的','The project has potential benefits for rural areas.'],
  ['predict','预测','It is difficult to predict future job markets.'],
  ['previous','以前的','The previous study reached a similar conclusion.'],
  ['principle','原则','The principle of fairness is important in education.'],
  ['process','过程','Writing is a process of planning and revising.'],
  ['proportion','比例','A large proportion of spending went to housing.'],
  ['pursue','追求','Many students pursue higher education abroad.'],
  ['range','范围','The course covers a wide range of topics.'],
  ['region','地区','The region depends heavily on tourism.'],
  ['regulate','监管','Governments may need to regulate online advertising.'],
  ['relevant','相关的','Examples should be relevant to the question.'],
  ['reliable','可靠的','Reliable data is essential for research.'],
  ['require','需要','The task requires careful planning.'],
  ['reside','居住','Many young adults reside in urban areas.'],
  ['resource','资源','Water is a limited resource.'],
  ['respond','回应','Companies must respond to consumer demand.'],
  ['restrict','限制','Some cities restrict private cars in the centre.'],
  ['retain','保留；记住','Spaced repetition helps learners retain vocabulary.'],
  ['reveal','揭示','The survey reveals a change in public opinion.'],
  ['sector','部门；领域','The service sector employs many graduates.'],
  ['shift','转变','There has been a shift towards remote work.'],
  ['specific','具体的','A specific example makes the argument stronger.'],
  ['stable','稳定的','The figure remained stable for three years.'],
  ['strategy','策略','A clear strategy improves exam preparation.'],
  ['structure','结构','Essay structure affects coherence.'],
  ['substitute','替代品','Public transport can be a substitute for private cars.'],
  ['sufficient','足够的','Candidates need sufficient practice before the exam.'],
  ['sustainable','可持续的','Sustainable development protects future generations.'],
  ['trend','趋势','The trend was upward between 2010 and 2020.'],
  ['valid','有效的；合理的','This is a valid point, but it needs evidence.'],
  ['vary','变化','Results vary according to age and background.']
];

if (typeof window !== 'undefined') {
  window.IELTS_WORD_BANK = IELTS_WORD_BANK.map(([word, meaning, example]) => ({ word, meaning, example }));
}
